name: Test & deploy dev

on: [push]

jobs:
  dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Run tests
      run: |
        pipenv run pytest -v -m "not integration"
    - name: Deploy to dev
      run: |
        pipenv run aws sqs create-queue --queue-name timereport-slack-command-dev --attributes VisibilityTimeout=60
        pipenv run aws sqs create-queue --queue-name timereport-slack-interactive-dev --attributes VisibilityTimeout=60
        pipenv run python template-config.py
        pipenv run chalice deploy --stage dev
      env:
        BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
        AWS_DEFAULT_REGION: "eu-north-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
